function src_menu_database(){
	/// @function src_menu_database()

global.pool_minuman =
[
"Air Mineral|5|Tawar|Minuman",
"Es Teh|8|Manis|Minuman",
"Teh Hangat|10|Manis|Minuman",
"Jeruk Hangat|12|Segar|Minuman",
"Jus Melon|15|Segar|Minuman",
"Jus Jeruk|18|Segar|Minuman",
"Jus Mangga|20|Segar|Minuman",
"Jus Alpukat|22|Segar|Minuman",
"Americano|25|Pahit|Minuman",
"Es Kopi Susu|28|Manis|Minuman",
"Cappuccino|30|Pahit|Minuman",
"Latte|32|Manis|Minuman",
"Matcha Latte|35|Manis|Minuman",
"Thai Tea|38|Manis|Minuman",
"Milkshake Coklat|40|Manis|Minuman",
"Milkshake Vanilla|42|Manis|Minuman",
"Cold Brew|45|Pahit|Minuman",
"Mocha|48|Manis|Minuman",
"Affogato|50|Manis|Minuman",
"Yakult Lychee|52|Segar|Minuman",
"Sparkling Lemon|55|Segar|Minuman",
"Mocktail Ocean|60|Segar|Minuman",
"Mocktail Sunset|65|Segar|Minuman",
"Blue Lagoon|70|Segar|Minuman",
"Dragon Drink|75|Segar|Minuman",
"Golden Latte|80|Manis|Minuman",
"Royal Tea|85|Manis|Minuman",
"Premium Espresso|90|Pahit|Minuman",
"Diamond Coffee|95|Pahit|Minuman",
"Galaxy Shake|100|Manis|Minuman",
"Cosmic Blend|105|Manis|Minuman",
"Infinity Brew|110|Pahit|Minuman",
"Legendary Latte|115|Manis|Minuman",
"Celestial Brew|120|Pahit|Minuman",
"Godly Elixir|125|Manis|Minuman"
];

global.pool_makanan =
[
"Nasi Putih|5|Tawar|Makanan",
"Mie Instan|8|Gurih|Makanan",
"Nasi Uduk|10|Gurih|Makanan",
"Mie Goreng|12|Gurih|Makanan",
"Mie Kuah|15|Gurih|Makanan",
"Bakso|18|Gurih|Makanan",
"Soto Ayam|20|Gurih|Makanan",
"Nasi Goreng|22|Gurih|Makanan",
"Ayam Geprek|25|Pedas|Makanan",
"Ayam Bakar|28|Gurih|Makanan",
"Ayam Katsu|30|Gurih|Makanan",
"Burger Beef|35|Gurih|Makanan",
"Cheese Burger|38|Gurih|Makanan",
"Pizza Slice|40|Gurih|Makanan",
"Spaghetti|42|Gurih|Makanan",
"Fish & Chips|45|Gurih|Makanan",
"Lasagna|48|Gurih|Makanan",
"Chicken Steak|50|Gurih|Makanan",
"Rendang|55|Gurih|Makanan",
"Nasi Kebuli|60|Gurih|Makanan",
"Katsu Curry|65|Gurih|Makanan",
"Ramen Premium|70|Gurih|Makanan",
"Beef Steak|75|Gurih|Makanan",
"Salmon Grill|80|Gurih|Makanan",
"Sushi Set|85|Gurih|Makanan",
"BBQ Platter|90|Gurih|Makanan",
"Roasted Duck|95|Gurih|Makanan",
"Wagyu Bowl|100|Gurih|Makanan",
"Seafood Platter|105|Gurih|Makanan",
"Premium Steak|110|Gurih|Makanan",
"Truffle Pasta|115|Gurih|Makanan",
"Lobster Plate|118|Gurih|Makanan",
"Royal Feast|120|Gurih|Makanan",
"Imperial Course|123|Gurih|Makanan",
"Celestial Banquet|125|Gurih|Makanan"
];

global.pool_cemilan =
[
"Kerupuk|5|Gurih|Cemilan",
"Cireng|7|Gurih|Cemilan",
"Kentang Goreng|10|Gurih|Cemilan",
"Pisang Goreng|12|Manis|Cemilan",
"Tahu Crispy|15|Gurih|Cemilan",
"Batagor|18|Gurih|Cemilan",
"Donat|20|Manis|Cemilan",
"Cookies|22|Manis|Cemilan",
"Brownies|25|Manis|Cemilan",
"Churros|28|Manis|Cemilan",
"Cupcake|30|Manis|Cemilan",
"Nachos|32|Gurih|Cemilan",
"Popcorn Caramel|35|Manis|Cemilan",
"Popcorn Cheese|38|Gurih|Cemilan",
"Waffle|40|Manis|Cemilan",
"Pancake|42|Manis|Cemilan",
"Ice Cream Cup|45|Manis|Cemilan",
"Gelato|48|Manis|Cemilan",
"Macaron|50|Manis|Cemilan",
"Cheese Cake|55|Manis|Cemilan",
"Red Velvet|60|Manis|Cemilan",
"Tiramisu|65|Manis|Cemilan",
"Chocolate Lava|70|Manis|Cemilan",
"Premium Donut|75|Manis|Cemilan",
"Belgian Waffle|80|Manis|Cemilan",
"Luxury Macaron|85|Manis|Cemilan",
"Golden Cookies|90|Manis|Cemilan",
"Diamond Cake|95|Manis|Cemilan",
"Royal Dessert|100|Manis|Cemilan",
"Galaxy Pie|105|Manis|Cemilan",
"Celestial Tart|110|Manis|Cemilan",
"Infinity Mousse|115|Manis|Cemilan",
"Legendary Dessert|120|Manis|Cemilan",
"Mythic Sweet|123|Manis|Cemilan",
"Godly Dessert|125|Manis|Cemilan"
];


}